version: '3.8'

services:
  cataloguer:
    build: .
    container_name: pokemon-cataloguer
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
    env_file:
      - .env
    environment:
      - DATA_DIR=/data
      - PUID=99
      - PGID=100
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
